require "user.lker"
require "user.options"
require "user.keymaps"
spec "user.colorscheme"
-- require ("user.devicons") -- manage with nixos
spec "user.treesitter"
-- spec ("user.mason") -- doesn't play nice with nixos
spec "user.schemastore"
spec "user.comment"
spec "user.whichkey"
spec "user.cmp"
spec "user.none-ls"
spec "user.illuminate"
spec "user.lualine"
spec "user.telescope"
spec "user.lspconfig"
spec "user.extras/copilot"
spec "user.extras/colorizer"
spec "user.extras/ufo"
require "user.lazy"
