require ("user/lker")
require ("user/options")
require ("user/keymaps")
spec ("user/devicons")
spec ("user/treesitter")
spec ("user/mason")
spec "user/schemastore"
spec "user/whichkey"
spec "user/lspconfig"
require ("user/lazy")
